from alpine
MAINTAINER Li YaLei <caidaoli@gmail.com>
# 替换阿里云源
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/' /etc/apk/repositories
RUN apk --update --no-cache  add  alpine-sdk gcc cmake   git  zsh jsoncpp-dev libevent-dev vim wget curl  unixodbc-dev
RUN wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true
RUN wget https://github.com/msgpack/msgpack-c/releases/download/cpp-2.0.0/msgpack-2.0.0.tar.gz && mkdir /msgpack && tar xzf msgpack-2.0.0.tar.gz -C /msgpack && cd /msgpack/msgpack-2.0.0 && cmake -DMSGPACK_CXX11=ON . && make install
ADD zshrc /root/.zshrc

VOLUME ["/app"]
workdir "/app"
#ENTRYPOINT ["zsh"]
